# **Recreating Figure 3C**
---
## **Inputs:**

| No. | File(s)             | Path                                                                        |Generated by| Used by | Description |
|-----|---------------------|-----------------------------------------------------------------------------|------------|---------|-------------|
|**1.**|`MA1_MA2_FG_Alp.csv` |`pipeline/`| Manually created | `shared_introgressions.py` y `coreVunique.R` |List of IDs and Phylogenetic Groups|
|**2.**|`{SAMPLE}_introSAPA_All_noOrth.csv`|`../../fig3A/pipeline/data/introgressions/`| Generated for figure 3A. | shared_introgressions.py |Introgressed genes on SAMPLE.|


*Note:* All paths are relative to this file, exceptions are signaled by a starting `/`.*

---
## **Scripts:**
| No. | Script             | Path                                                                        | Output | Description |
|-----|--------------------|-----------------------------------------------------------------------------|--------|-------------|
|**1.**|`shared_introgressions.py`|`pipeline/scripts/`|CSVs with a matrix of presence abscence of introgressions|Runs all the pipeline: 1. Compute coverage depth, 2. obtain coverage statistics, 3. filters and converts gff into txt, 4. find genes with coverage and 5. obtain introgressions.|
|**2.**|`coreVunique.R`|`pipeline/scripts/`|Multiple sges as well as several bash files on `bin/sge/`|Runs all the pipeline: 1. Compute coverage depth, 2. obtain coverage statistics, 3. filters and converts gff into txt, 4. find genes with coverage and 5. obtain introgressions.|


### *Packages/Dependencies:*
**1.**

---
## **Outputs:**
| No. | File | Path | Description |
|-----|------|------|-------------|
|**1.**|`{SAMPLE_introSAPA_All_noOrth.csv}`|`pipeline/introgressions/`|CSV file with introgressions per sample, includes information about the introgressed gene.|

*Note:* Several intermediate files are created but not all of them are stored. Only relevant files are listed above.

---
## **Execution:**
**1.**
```
cd pipeline
python scripts/shared_introgressions.py -s MA1_MA2_FG_Alp.csv -o data/ -f ../../fig3A/pipeline/data/introgressions/ -p MA1MA2FGAlp
Rscript scripts/coreVunique.R data/MA1MA2FGAlp_common_introgressions_in_strains.csv data/frequencies.pdf
```
